### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by nicolamarangoni** [exasol/hadoop-etl-udfs#43]
Hello, we are trying to import a table containing 40k row but we get the error
`java.lang.OutOfMemoryError: Java heap space`.

Here the complete stack trace:

```
19/10/17 01:29:44 user=twitt uuid=bca0 DEBUG ExasolImpl: Executing sql in exasol: 
 
IMPORT INTO schema_name.table_name
FROM SCRIPT UDF_SCHEMA.IMPORT_HCAT_TABLE WITH
HCAT_DB = 'schema_name'
HCAT_TABLE = 'table_name'
HCAT_ADDRESS = 'thrift://hive-hostname:9083'
HCAT_USER = 'username'
HDFS_USER = 'username'
PARALLELISM = 'nproc() * 2'
HDFS_URL = 'hdfs://namenodehost1:8020,hdfs://namenodehost2:8020'

19/10/17 01:31:17 user=twitt uuid=bca0 DEBUG ProcessStepExecution: Lock released for table 'campaignlineitem'
19/10/17 01:31:17 user=twitt uuid=bca0 ERROR Main$: VM error: 
java.lang.OutOfMemoryError: Java heap space
Stack trace:
java.base/java.util.Arrays.copyOf(Arrays.java:3689)
java.base/java.util.ArrayList.grow(ArrayList.java:237)
java.base/java.util.ArrayList.grow(ArrayList.java:242)
java.base/java.util.ArrayList.add(ArrayList.java:485)
java.base/java.util.ArrayList.add(ArrayList.java:498)
com.exasol.hadoop.scriptclasses.ImportHiveTableFiles.run(ImportHiveTableFiles.java:82)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.exasol.ExaWrapper.run(ExaWrapper.java:168) (Session: 1647557764979252510)
19/10/17 01:31:17 user=twitt uuid=bca0 DEBUG Main$: VM error: 
java.lang.OutOfMemoryError: Java heap space
Stack trace:
java.base/java.util.Arrays.copyOf(Arrays.java:3689)
java.base/java.util.ArrayList.grow(ArrayList.java:237)
java.base/java.util.ArrayList.grow(ArrayList.java:242)
java.base/java.util.ArrayList.add(ArrayList.java:485)
java.base/java.util.ArrayList.add(ArrayList.java:498)
com.exasol.hadoop.scriptclasses.ImportHiveTableFiles.run(ImportHiveTableFiles.java:82)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.exasol.ExaWrapper.run(ExaWrapper.java:168) (Session: 1647557764979252510)
com.exasol.jdbc.DataException: VM error: 
java.lang.OutOfMemoryError: Java heap space
Stack trace:
java.base/java.util.Arrays.copyOf(Arrays.java:3689)
java.base/java.util.ArrayList.grow(ArrayList.java:237)
java.base/java.util.ArrayList.grow(ArrayList.java:242)
java.base/java.util.ArrayList.add(ArrayList.java:485)
java.base/java.util.ArrayList.add(ArrayList.java:498)
com.exasol.hadoop.scriptclasses.ImportHiveTableFiles.run(ImportHiveTableFiles.java:82)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
com.exasol.ExaWrapper.run(ExaWrapper.java:168) (Session: 1647557764979252510)
	at com.exasol.jdbc.ExceptionFactory.createSQLException(ExceptionFactory.java:33)
	at com.exasol.jdbc.EXASQLException.getSQLExceptionIntern(EXASQLException.java:50)
	at com.exasol.jdbc.AbstractEXAPreparedStatement.execute(AbstractEXAPreparedStatement.java:216)
	at com.exasol.jdbc.AbstractEXAPreparedStatement.executeQuery(AbstractEXAPreparedStatement.java:369)
	at com.prosiebensat1.pharos.connection.ExasolImpl.executeSql(Exasol.scala:200)
	at com.prosiebensat1.pharos.connection.ExasolImpl.importTableFromHive(Exasol.scala:495)
	at com.prosiebensat1.pharos.metadata.TransformationView.replaceChangedPartitions(TransformationView.scala:429)
	at com.prosiebensat1.pharos.metadata.TransformationView.materialize(TransformationView.scala:312)
	at com.prosiebensat1.pharos.scheduler.ProcessStepExecution$$anonfun$run$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(ProcessStepExecution.scala:200)
	at com.prosiebensat1.pharos.scheduler.ProcessStepExecution$$anonfun$run$1$$anonfun$apply$mcV$sp$2.apply(ProcessStepExecution.scala:200)
	at com.prosiebensat1.pharos.scheduler.ProcessStepExecution$$anonfun$run$1$$anonfun$apply$mcV$sp$2.apply(ProcessStepExecution.scala:200)
	at com.prosiebensat1.pharos.utils.SparkJobSupervisor$.allowSupervisedRun(SparkJobSupervisor.scala:55)
	at com.prosiebensat1.pharos.scheduler.ProcessStepExecution$$anonfun$run$1.apply$mcV$sp(ProcessStepExecution.scala:199)
	at com.prosiebensat1.pharos.scheduler.ProcessStepExecution$$anonfun$run$1.apply(ProcessStepExecution.scala:102)
	at com.prosiebensat1.pharos.scheduler.ProcessStepExecution$$anonfun$run$1.apply(ProcessStepExecution.scala:102)
	at com.prosiebensat1.pharos.scheduler.ProcessExecution$.withRetry(ProcessExecution.scala:323)
	at com.prosiebensat1.pharos.scheduler.ProcessStepExecution.run(ProcessStepExecution.scala:102)
	at com.prosiebensat1.pharos.scheduler.ProcessExecution$$anonfun$runProcessStepsSequentially$1.apply(ProcessExecution.scala:186)
	at com.prosiebensat1.pharos.scheduler.ProcessExecution$$anonfun$runProcessStepsSequentially$1.apply(ProcessExecution.scala:183)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.prosiebensat1.pharos.scheduler.ProcessExecution.runProcessStepsSequentially(ProcessExecution.scala:183)
	at com.prosiebensat1.pharos.scheduler.ProcessExecution.run(ProcessExecution.scala:141)
	at com.prosiebensat1.pharos.scheduler.ProcessExecution$.executeProcessRun(ProcessExecution.scala:310)
	at com.prosiebensat1.pharos.ui.ProcessExecutionCommand.run(ProcessExecutionCommand.scala:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1681)
	at picocli.CommandLine.access$900(CommandLine.java:143)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2020)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1987)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1854)
	at picocli.CommandLine.execute(CommandLine.java:1783)
	at com.prosiebensat1.pharos.Main$.delayedEndpoint$com$prosiebensat1$pharos$Main$1(Main.scala:24)
	at com.prosiebensat1.pharos.Main$delayedInit$body.apply(Main.scala:14)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.prosiebensat1.pharos.Main$.main(Main.scala:14)
	at com.prosiebensat1.pharos.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/10/17 01:31:17 user=twitt uuid=bca0 ERROR Main$: Execution stopped due to error
```

**Comment by morazow** [comment]
Hello @nicolamarangoni,

Thanks for submitting the issue!

Since hadoop-etl-udfs read underlying files from Hive tables that are stored in Hdfs, could you please check if the Hive table have too many files? 

From the initial look into error, it seems that the exception happens when gathering the list of files for the import process.

**Comment by morazow** [comment]
Hello @nicolamarangoni,

I am going to close this issue. Please feel free to open new issue if there are still questions.
